[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<main.cpp>
lib_deps =
  knolleary/PubSubClient@^2.8

[env:relay-click]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<experiments/relay_click_main.cpp>

[env:sensor-probe]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<experiments/sensor_probe_main.cpp>

[env:native]
platform = native
test_build_src = no
